CREATE TABLE IF NOT EXISTS servico (
    id SERIAL primary key,
    horas_banheiro integer NOT NULL,
    horas_cozinha integer NOT NULL,
    horas_outros integer NOT NULL,
    horas_quarto integer NOT NULL,
    horas_quintal integer NOT NULL,
    horas_sala integer NOT NULL,
    icone character varying(14) NOT NULL,
    nome character varying(50) NOT NULL,
    percentagem_comissao numeric(38,2) NOT NULL,
    posicao integer NOT NULL,
    qtd_horas integer NOT NULL,
    valor_banheiro numeric(38,2) NOT NULL,
    valor_cozinha numeric(38,2) NOT NULL,
    valor_minimo numeric(38,2) NOT NULL,
    valor_outros numeric(38,2) NOT NULL,
    valor_quarto numeric(38,2) NOT NULL,
    valor_quintal numeric(38,2) NOT NULL,
    valor_sala numeric(38,2) NOT NULL
);